# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Classes\ECEN_5783\Projects\Project 1\Temp_o_Matic\designer\tempomatic.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 868)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(34, 35, 37);\n"
"color: rgb(241, 241, 241);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.header = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        self.header.setFont(font)
        self.header.setStyleSheet("background-color: rgb(90, 93, 98);")
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_title = QtWidgets.QLabel(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_title.sizePolicy().hasHeightForWidth())
        self.app_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.app_title.setFont(font)
        self.app_title.setObjectName("app_title")
        self.horizontalLayout.addWidget(self.app_title, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.header, 0, 0, 1, 1)
        self.main = QtWidgets.QWidget(self.centralwidget)
        self.main.setObjectName("main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.system = QtWidgets.QWidget(self.main)
        self.system.setMinimumSize(QtCore.QSize(400, 0))
        self.system.setObjectName("system")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.system)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.system_frame = QtWidgets.QGroupBox(self.system)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_frame.sizePolicy().hasHeightForWidth())
        self.system_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.system_frame.setFont(font)
        self.system_frame.setObjectName("system_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.system_frame)
        self.gridLayout_3.setContentsMargins(10, 5, 10, 15)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.system_status_header = QtWidgets.QLabel(self.system_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_status_header.sizePolicy().hasHeightForWidth())
        self.system_status_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.system_status_header.setFont(font)
        self.system_status_header.setObjectName("system_status_header")
        self.gridLayout_3.addWidget(self.system_status_header, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.logging_header = QtWidgets.QLabel(self.system_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logging_header.sizePolicy().hasHeightForWidth())
        self.logging_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.logging_header.setFont(font)
        self.logging_header.setObjectName("logging_header")
        self.gridLayout_3.addWidget(self.logging_header, 6, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.sensor_status_header = QtWidgets.QLabel(self.system_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.sensor_status_header.setFont(font)
        self.sensor_status_header.setObjectName("sensor_status_header")
        self.gridLayout_3.addWidget(self.sensor_status_header, 2, 0, 1, 1)
        self.logging_switch = SwitchButton(self.system_frame)
        self.logging_switch.setMinimumSize(QtCore.QSize(50, 0))
        self.logging_switch.setProperty("thumb_radius", 10)
        self.logging_switch.setProperty("track_radius", 5)
        self.logging_switch.setObjectName("logging_switch")
        self.gridLayout_3.addWidget(self.logging_switch, 6, 1, 1, 1, QtCore.Qt.AlignRight)
        self.temp_unit_header = QtWidgets.QLabel(self.system_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_unit_header.sizePolicy().hasHeightForWidth())
        self.temp_unit_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.temp_unit_header.setFont(font)
        self.temp_unit_header.setObjectName("temp_unit_header")
        self.gridLayout_3.addWidget(self.temp_unit_header, 7, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.sensor_status = QtWidgets.QLabel(self.system_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.sensor_status.setFont(font)
        self.sensor_status.setObjectName("sensor_status")
        self.gridLayout_3.addWidget(self.sensor_status, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.system_status = QtWidgets.QLabel(self.system_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_status.sizePolicy().hasHeightForWidth())
        self.system_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.system_status.setFont(font)
        self.system_status.setObjectName("system_status")
        self.gridLayout_3.addWidget(self.system_status, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.temp_units = TempSwitchButton(self.system_frame)
        self.temp_units.setMinimumSize(QtCore.QSize(45, 0))
        self.temp_units.setProperty("thumb_radius", 9)
        self.temp_units.setObjectName("temp_units")
        self.gridLayout_3.addWidget(self.temp_units, 7, 1, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.system_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.monitor = QtWidgets.QGroupBox(self.system)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitor.sizePolicy().hasHeightForWidth())
        self.monitor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.monitor.setFont(font)
        self.monitor.setObjectName("monitor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.monitor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.display = QtWidgets.QWidget(self.monitor)
        self.display.setObjectName("display")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.display)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.temp_reading_frame = QtWidgets.QGroupBox(self.display)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.temp_reading_frame.setFont(font)
        self.temp_reading_frame.setStyleSheet("color: rgb(170, 85, 255);")
        self.temp_reading_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_reading_frame.setFlat(False)
        self.temp_reading_frame.setObjectName("temp_reading_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.temp_reading_frame)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.temp_reading = QtWidgets.QLabel(self.temp_reading_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.temp_reading.setFont(font)
        self.temp_reading.setObjectName("temp_reading")
        self.verticalLayout_5.addWidget(self.temp_reading, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_4.addWidget(self.temp_reading_frame)
        self.humidity_reading_frame = QtWidgets.QGroupBox(self.display)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.humidity_reading_frame.setFont(font)
        self.humidity_reading_frame.setStyleSheet("color: rgb(255, 170, 0);")
        self.humidity_reading_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity_reading_frame.setFlat(False)
        self.humidity_reading_frame.setObjectName("humidity_reading_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.humidity_reading_frame)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.humidity_reading = QtWidgets.QLabel(self.humidity_reading_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.humidity_reading.setFont(font)
        self.humidity_reading.setObjectName("humidity_reading")
        self.verticalLayout_6.addWidget(self.humidity_reading, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_4.addWidget(self.humidity_reading_frame)
        self.verticalLayout.addWidget(self.display)
        self.timestamp_widget = QtWidgets.QWidget(self.monitor)
        self.timestamp_widget.setObjectName("timestamp_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.timestamp_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.time_header = QtWidgets.QLabel(self.timestamp_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.time_header.setFont(font)
        self.time_header.setObjectName("time_header")
        self.gridLayout_4.addWidget(self.time_header, 0, 0, 1, 1)
        self.timestamp = QtWidgets.QLabel(self.timestamp_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.timestamp.setFont(font)
        self.timestamp.setObjectName("timestamp")
        self.gridLayout_4.addWidget(self.timestamp, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.timestamp_widget)
        self.current_reading_button = QtWidgets.QPushButton(self.monitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_reading_button.sizePolicy().hasHeightForWidth())
        self.current_reading_button.setSizePolicy(sizePolicy)
        self.current_reading_button.setMinimumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.current_reading_button.setFont(font)
        self.current_reading_button.setStyleSheet("QPushButton \n"
"{\n"
"    background-repeat: no;\n"
"    background-position: center left;\n"
"    border: outset;\n"
"    background-color: rgba(73, 147, 220, .7);\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgba(73, 147, 220, .7);\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgba(73, 147, 220, .8);\n"
"}")
        self.current_reading_button.setObjectName("current_reading_button")
        self.verticalLayout.addWidget(self.current_reading_button, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.monitor)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.alarms = QtWidgets.QGroupBox(self.system)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alarms.sizePolicy().hasHeightForWidth())
        self.alarms.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.alarms.setFont(font)
        self.alarms.setObjectName("alarms")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.alarms)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.temp_alarm_widget = QtWidgets.QWidget(self.alarms)
        self.temp_alarm_widget.setObjectName("temp_alarm_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.temp_alarm_widget)
        self.verticalLayout_8.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.temp_alarm_header = QtWidgets.QLabel(self.temp_alarm_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.temp_alarm_header.setFont(font)
        self.temp_alarm_header.setObjectName("temp_alarm_header")
        self.verticalLayout_8.addWidget(self.temp_alarm_header, 0, QtCore.Qt.AlignHCenter)
        self.temp_alarm_setting = QtWidgets.QLabel(self.temp_alarm_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_alarm_setting.sizePolicy().hasHeightForWidth())
        self.temp_alarm_setting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.temp_alarm_setting.setFont(font)
        self.temp_alarm_setting.setObjectName("temp_alarm_setting")
        self.verticalLayout_8.addWidget(self.temp_alarm_setting, 0, QtCore.Qt.AlignHCenter)
        self.temp_alarm = QtWidgets.QSlider(self.temp_alarm_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_alarm.sizePolicy().hasHeightForWidth())
        self.temp_alarm.setSizePolicy(sizePolicy)
        self.temp_alarm.setMinimumSize(QtCore.QSize(150, 0))
        self.temp_alarm.setOrientation(QtCore.Qt.Horizontal)
        self.temp_alarm.setObjectName("temp_alarm")
        self.verticalLayout_8.addWidget(self.temp_alarm)
        self.horizontalLayout_5.addWidget(self.temp_alarm_widget)
        self.humid_alarm_widget = QtWidgets.QWidget(self.alarms)
        self.humid_alarm_widget.setObjectName("humid_alarm_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.humid_alarm_widget)
        self.verticalLayout_7.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.humidity_alarm_header = QtWidgets.QLabel(self.humid_alarm_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.humidity_alarm_header.setFont(font)
        self.humidity_alarm_header.setObjectName("humidity_alarm_header")
        self.verticalLayout_7.addWidget(self.humidity_alarm_header, 0, QtCore.Qt.AlignHCenter)
        self.humidity_alarm_setting = QtWidgets.QLabel(self.humid_alarm_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidity_alarm_setting.sizePolicy().hasHeightForWidth())
        self.humidity_alarm_setting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        self.humidity_alarm_setting.setFont(font)
        self.humidity_alarm_setting.setObjectName("humidity_alarm_setting")
        self.verticalLayout_7.addWidget(self.humidity_alarm_setting, 0, QtCore.Qt.AlignHCenter)
        self.humidity_alarm = QtWidgets.QSlider(self.humid_alarm_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humidity_alarm.sizePolicy().hasHeightForWidth())
        self.humidity_alarm.setSizePolicy(sizePolicy)
        self.humidity_alarm.setMinimumSize(QtCore.QSize(150, 0))
        self.humidity_alarm.setOrientation(QtCore.Qt.Horizontal)
        self.humidity_alarm.setObjectName("humidity_alarm")
        self.verticalLayout_7.addWidget(self.humidity_alarm)
        self.horizontalLayout_5.addWidget(self.humid_alarm_widget)
        self.verticalLayout_3.addWidget(self.alarms)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.system)
        self.plot_frame = QtWidgets.QWidget(self.main)
        self.plot_frame.setObjectName("plot_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.plot_frame)
        self.verticalLayout_2.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot = PlotWidget(self.plot_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setObjectName("plot")
        self.verticalLayout_2.addWidget(self.plot)
        self.plot_interface = QtWidgets.QWidget(self.plot_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_interface.sizePolicy().hasHeightForWidth())
        self.plot_interface.setSizePolicy(sizePolicy)
        self.plot_interface.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.plot_interface.setFont(font)
        self.plot_interface.setObjectName("plot_interface")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.plot_interface)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plot_options = QtWidgets.QGroupBox(self.plot_interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_options.sizePolicy().hasHeightForWidth())
        self.plot_options.setSizePolicy(sizePolicy)
        self.plot_options.setMinimumSize(QtCore.QSize(0, 135))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.plot_options.setFont(font)
        self.plot_options.setObjectName("plot_options")
        self.gridLayout = QtWidgets.QGridLayout(self.plot_options)
        self.gridLayout.setObjectName("gridLayout")
        self.temp_plot_switch = SwitchButton(self.plot_options)
        self.temp_plot_switch.setMinimumSize(QtCore.QSize(50, 0))
        self.temp_plot_switch.setProperty("thumb_radius", 10)
        self.temp_plot_switch.setProperty("track_radius", 5)
        self.temp_plot_switch.setObjectName("temp_plot_switch")
        self.gridLayout.addWidget(self.temp_plot_switch, 0, 1, 1, 1)
        self.temp_plot_header = QtWidgets.QLabel(self.plot_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_plot_header.sizePolicy().hasHeightForWidth())
        self.temp_plot_header.setSizePolicy(sizePolicy)
        self.temp_plot_header.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.temp_plot_header.setFont(font)
        self.temp_plot_header.setObjectName("temp_plot_header")
        self.gridLayout.addWidget(self.temp_plot_header, 0, 0, 1, 1)
        self.humid_plot_header = QtWidgets.QLabel(self.plot_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.humid_plot_header.sizePolicy().hasHeightForWidth())
        self.humid_plot_header.setSizePolicy(sizePolicy)
        self.humid_plot_header.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.humid_plot_header.setFont(font)
        self.humid_plot_header.setObjectName("humid_plot_header")
        self.gridLayout.addWidget(self.humid_plot_header, 1, 0, 1, 1)
        self.humid_plot_switch = SwitchButton(self.plot_options)
        self.humid_plot_switch.setMinimumSize(QtCore.QSize(50, 0))
        self.humid_plot_switch.setProperty("thumb_radius", 10)
        self.humid_plot_switch.setProperty("track_radius", 5)
        self.humid_plot_switch.setObjectName("humid_plot_switch")
        self.gridLayout.addWidget(self.humid_plot_switch, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.plot_options)
        self.plot_controls = QtWidgets.QWidget(self.plot_interface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_controls.sizePolicy().hasHeightForWidth())
        self.plot_controls.setSizePolicy(sizePolicy)
        self.plot_controls.setObjectName("plot_controls")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.plot_controls)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plot_button = QtWidgets.QPushButton(self.plot_controls)
        self.plot_button.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        self.plot_button.setFont(font)
        self.plot_button.setStyleSheet("QPushButton \n"
"{\n"
"    background-repeat: no;\n"
"    background-position: center left;\n"
"    border: outset;\n"
"    background-color: rgba(73, 147, 220, .7);\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    background-color: rgba(73, 147, 220, .7);\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    background-color: rgba(73, 147, 220, .8);\n"
"}")
        self.plot_button.setObjectName("plot_button")
        self.horizontalLayout_3.addWidget(self.plot_button)
        self.verticalLayout_4.addWidget(self.plot_controls)
        self.verticalLayout_2.addWidget(self.plot_interface)
        self.horizontalLayout_2.addWidget(self.plot_frame)
        self.gridLayout_2.addWidget(self.main, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.app_title.setText(_translate("MainWindow", "Temp-o-Matic"))
        self.system_frame.setTitle(_translate("MainWindow", "System"))
        self.system_status_header.setText(_translate("MainWindow", "System Status"))
        self.logging_header.setText(_translate("MainWindow", "Logging"))
        self.sensor_status_header.setText(_translate("MainWindow", "Sensor Status"))
        self.temp_unit_header.setText(_translate("MainWindow", "Temperature Units"))
        self.sensor_status.setText(_translate("MainWindow", "Status"))
        self.system_status.setText(_translate("MainWindow", "Status"))
        self.monitor.setTitle(_translate("MainWindow", "Monitor"))
        self.temp_reading_frame.setTitle(_translate("MainWindow", "Temperature"))
        self.temp_reading.setText(_translate("MainWindow", "39.1°C"))
        self.humidity_reading_frame.setTitle(_translate("MainWindow", "Humidity"))
        self.humidity_reading.setText(_translate("MainWindow", "48.1%"))
        self.time_header.setText(_translate("MainWindow", "Time Received:"))
        self.timestamp.setText(_translate("MainWindow", "01/01/19 12:22:03"))
        self.current_reading_button.setText(_translate("MainWindow", "Now"))
        self.alarms.setTitle(_translate("MainWindow", "Alarms"))
        self.temp_alarm_header.setText(_translate("MainWindow", "Temperature"))
        self.temp_alarm_setting.setText(_translate("MainWindow", "39°C"))
        self.humidity_alarm_header.setText(_translate("MainWindow", "Humidity"))
        self.humidity_alarm_setting.setText(_translate("MainWindow", "22%"))
        self.plot_options.setTitle(_translate("MainWindow", "Plot Options"))
        self.temp_plot_header.setText(_translate("MainWindow", "Temperature"))
        self.humid_plot_header.setText(_translate("MainWindow", "Humidity"))
        self.plot_button.setText(_translate("MainWindow", "Plot"))
from src.plotter import PlotWidget
from src.ui.switchbutton import SwitchButton
from src.ui.tempswitchbutton import TempSwitchButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
